# Generated by Django 4.1.7 on 2023-04-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallary',
            old_name='photo_1',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='gallary2',
            old_name='photo_1',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='photo_main',
        ),
        migrations.RemoveField(
            model_name='gallary2',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='gallary2',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='gallary2',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='gallary2',
            name='photo_main',
        ),
    ]
