# Generated by Django 4.1.7 on 2023-04-04 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('post_imgage', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('post_intro', models.CharField(max_length=500)),
                ('post_main', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authors.author')),
            ],
        ),
    ]
