# Generated by Django 4.1.7 on 2023-04-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_imgage',
            new_name='post_image',
        ),
    ]
