# Generated by Django 4.1.1 on 2023-04-06 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_imgage_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_sneakpeak',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
